# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78bdbfff9427704af674bfa2d3891b4bf33f49c19c68e1d2125d9bcaa0e8c311ebcb6d6ff9667f324d1cf10c91b597a4a9d7ffb8ee5767245072826e4e9e1f8b

test:
  secret_key_base: 71a9fa446f66ee165014e2ed0117bc25fedaca4770dfb924866f2a023dabfa55b449a0844c3fe86f758f760dbc68cfbdc22557273c83f6e5f4d946d928555a68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
